char_B = ord('B')
char_C = ord('C')
char_D = ord('D')
char_b = ord('b')
char_c = ord('c')
char_d = ord('d')
char_0 = ord('0')
char_1 = ord('1')
char_2 = ord('2')
char_dollar = ord('$')
char_star = ord('*')
char_plus = ord('+')
char_space = ord(' ')

print(f"char for B: {char_B}, char for C: {char_C}, char for D: {char_D}, char for b: {char_b}, char for c: {char_c}, char for d: {char_d}, char for 0: {char_0}, char for 1: {char_1}, char for 2: {char_2}, char for $: {char_dollar}, char for *: {char_star}, char for +: {char_plus}, char for space: {char_space}")
